---
title: "Stats4Good"
author: "Luís G. Silva e Silva"
date: 2018-03-16T20:36:00-03:00
categories: ["Projects"]
tags: ["R", "Data Visualization", "Applied Statistics"]
banner: "projects/stats4good/stats4good.png"
summary: "The Stats4Good is a group founded in 2016 by graduate students of the Statistics Department from Universidade Federal de Minas Gerais, located in Belo Horizonte, Brazil. The group has aimed to provide statistical analysis that can help the society. The Stats4Good principles are Teaching, Learning and Discussing."
---
O Stats4Good é um grupo de estudantes entusiastas da ciência dos dados criado em 2016. Nosso objetivo é fornecer estatísticas e análise de dados como ferramentas de auxilio à sociedade. Além disso, os pilares do grupo são: Ensinar, Aprender e Discutir.

```{r setup, include=FALSE}
knitr::opts_knit$set(base.dir = 'projetos/stats4good/')
```

# Descrição

O Stats4Good é um grupo de estudantes entusiastas da ciência dos dados criado em 2016. Nosso objetivo é fornecer estatísticas e análise de dados como ferramentas de auxilio à sociedade. Além disso, os pilares do grupo são: Ensinar, Aprender e Discutir.

# Objetivos

O objetivo principal é a utilização de dados livres para prover informações de valor para a sociedade. Muitas são as fontes de dados disponíveis no Brasil. Porém, nem toda a população possui o conhecimento necessário para obter tais dados de forma simples. Além disso o processo de limpeza, manipulação e geração de informações não é uma tarefa trivial. Desta forma, o Stats4Good através de profissionais capacitados atua na geração de informações para a população a respeito de assuntos relevantes. Hoje (16/03/2016) o grupo trabalha em dois projetos: (1) criação de uma ferramente de visualização dos dados do portal da transparência (http://www.portaltransparencia.gov.br); (2) criação de uma plataforma cujo objetivo é descrever o problema do estupro em mulheres no Brasil.

# Tecnologias

Diversas são as tecnólogias utilizadas visto que os projetos atuam desde a extração dos dados até a visualização de dados. No blog do grupo alguns tutoriais podem ser encontrados (https://stats4good.github.io/blog/).

# Período de atuação

De Março de 2016 até o presente.