---
title: "Datalive"
author: "Luís G. Silva e Silva"
date: 2018-03-16T20:38:00-03:00
categories: ["Projects"]
tags: ["R", "Machine Learning", "Data Mining", "Marketing", "Applied Statistics"]
banner: "projects/datalive/datalive.png"
summary: "Entender o comportamento dos seus clientes é crucial para grandes empresas. De posse do conhecimento do comportamento de seus clientes as empresas podem fornecer produtos de forma mais assertiva e no momento mais oportuno. Visando isto a Datalive propõe a integração entre o comportamento online e offline visando obter um conhecimento mais rico a respeito dos clientes."
---

```{r setup, include=FALSE}
knitr::opts_knit$set(base.dir = 'projetos/infosas/')
```

# Descrição

Entender o comportamento dos seus clientes é crucial para grandes empresas. De posse do conhecimento do comportamento de seus clientes as empresas podem fornecer produtos de forma mais assertiva e no momento mais oportuno. Visando isto a Datalive propõe a integração entre o comportamento _online_ e _offline_ visando obter um conhecimento mais rico a respeito dos clientes.

# Objetivos

Como objetivos primários podemos citar o entendimento dos motivos que motivam um usuário a se identificar nos sites das empresas além de entender em qual momento isto ocorre. De posse deste conhecimento é possível solicitar identificação de outros clientes que estejam sob identificação iminente. 

Dada a identificação dos potenciais clientes o próximo passo é entender o processo de compra e, de forma similar, conquistar potenciais clientes cujas características sejam similares às já observadas anteriormente.

# Tecnologias

Como solução para os problemas iniciais foram gerados webservices que dado às características de um determinado usuário retornava uma decisão a ser tomada em relação a sua navegação. Para isto foram utilizados diversos pacotes no R:

+ plumber: Criação dos webservices
+ stringr: Manipulação de strings
+ dplyr: Manipulação de grandes bases de dados
+ data.table: Manipulação de grandes bases de dados

# Minha função

+ Criar e dar manutenção nos _webservices_
+ Pesquisar por técnicas aplicáveis aos problemas
+ Implementação das técnicas

# Período de atuação

De Outubro de 2017 até Fevereiro de 2018