---
title: "Curso R"
author: "Luís G. Silva e Silva"
date: 2018-03-16T20:37:00-03:00
categories: ["Projects"]
tags: ["R basics", "Coaching"]
banner: "projects/curso_r/curso_r.png"
summary: "A linguagem R vem se tornando cada vez mais popular entre grandes empresas. Esta popularidade se deve ao fato do R ser um _software_ livre aplicável em diversos contextos. Além disso, devido a sua popularidade atual está cada vez mais simples encontrar soluções para problemas práticos utilizando este _Software_."
---

```{r setup, include=FALSE}
knitr::opts_knit$set(base.dir = 'projetos/curso_r/')
```

# Descrição

A linguagem R vem se tornando cada vez mais popular entre grandes empresas. Esta popularidade se deve ao fato do R ser um _software_ livre aplicável em diversos contextos. Além disso, devido a sua popularidade atual está cada vez mais simples encontrar soluções para problemas práticos utilizando este _Software_.

# Objetivos

Dado a vasta aplicabilidade do _software_ R, a empresa Vallourec solicitou à UFMG um curso introdutório em R além de dois módulos extras: _Machine Learning_ e Controle Estatístico do Processo. Ao total o material do curso foi lecionado em um período de 40 horas.

# Tecnologias

Para facilitar a edição dos módulos e a padronização dos materiais pela equipe desenvolvedora, o material de aula foi desenvolvido no R utilizando o pacote _Rmarkdown_.

# Período de atuação

O curso foi ministrado em Dezembro de 2016.